export enum AuditAction {
  CREATE = 'CREATE',
  UPDATE = 'UPDATE',
  DELETE = 'DELETE',
  ACCEPT = 'ACCEPT',
  REJECT = 'REJECT',
  APPROVE = 'APPROVE',
  SUSPEND = 'SUSPEND',
  UNSUSPEND = 'UNSUSPEND',
  PAYMENT = 'PAYMENT',
  REFUND = 'REFUND',
  ACCESS = 'ACCESS',
  EXPORT = 'EXPORT',
}

